#parameter: value #you can add the reference as a comment #https://iopscience.iop.org/article/10.3847/1538-3881/aa6e01/pdf
magK: 7.853 #stell. magnitude in K band
Ts: 6290 #stellar Temperature in Kelvin
metal: -0.24 #stell. metallicity
logg: 4.29 #stell. logg
Rp_earth: 3.95 #not needed if user uses own model
Rs_sun: 1.18 #not needed if user uses own model
D: 4.693 #transit duration in hours
###
instrument: NIRSpec PRISM
noccultations: 2 #number of transits
R: 50 #resolution, definition: R = lambda_mid / delta_lambda
baseline: 1 #fraction in and out of transit
###
output: True #set if output should be saved
###
path_to_model: /home/zieba/Desktop/Data/HD106315c/hd106315c_metals_offsetcorr.txt #set to False if not wanted
w_unit: um #set to "cm", "um","nm" ,"Angs", "sec" (for phase curves)

