#parameter: value #you can add the reference as a comment #https://iopscience.iop.org/article/10.3847/1538-3881/aa6e01/pdf
magK: 7.853 #magnitude in K band
Ts: 6290
metal: -0.24
logg: 4.29
Rp_earth: 3.95 #not needed if user uses own model
Rs_sun: 1.18 #not needed if user uses own model
D: 4.693 #transit duration in hours
###
instrument: NIRCam F444W
noccultations: 1
R: 50 #STUPID
baseline: 1
###
output: True #set if output should be saved
###
path_to_model: /home/zieba/Desktop/Data/HD106315c/hd106315c_clouds_offsetcorr.txt #set to False if not wanted
w_unit: um #set to "cm", "um","nm" ,"Angs", "sec" (for phase curves)

